### PR TITLE
Support gunicorn 19.6.0

### PR DESCRIPTION
**Pull request by jacobsvante**
rainbow-saddle 0.3.2 breaks with latest gunicorn version because pid is saved to a new file location since commit https://github.com/benoitc/gunicorn/commit/418f140445c050af541abeb02835c6c78b2a71f0. (And now gunicorn saves the new master pid instead of the old one).

Please note that this commit drops support for all previous versions of gunicorn. Supporting both is definitely possible, but I’m happy with supporting only the new better signal handling.

### CODE REVIEW

**Comment by flupke** [comment]
Thanks, could you update the changelog in NEWS.txt?

**Comment by flupke** [comment]
And bump the major version to 0.4.0 too, as this is a breaking change.

**Comment by jacobsvante** [comment]
Done!

**Comment by flupke** [comment]
Thank you very much, I uploaded the release to pypi.

**Pull request merged**
